/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 25.08.2026 18:52:03

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1584;
#else
constexpr int kTensorArenaSize = 560;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,18 } };
const TfArray<1, float> quant0_scale = { 1, { 0.018292130902409554, } };
const TfArray<1, int> quant0_zero = { 1, { 31 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { 1, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00010491649300092831, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  -1, -50, 94, -78, 44, -6, -103, -52, -26, -100, 
  -127, -57, 43, -56, -46, 8, 52, 10, -41, -65, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0064059300348162651, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 11, -6, 1, 3, 5, 0, 12, 3, -16, 8, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00010898432083195075, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  -34, 54, 50, -51, 67, 59, -38, -41, -54, -50, 79, -9, -70, -15, 110, 76, -35, 70, -54, -67, 
  -45, 36, -31, 16, 5, 5, -23, 31, -6, -38, 55, -67, 43, 31, -19, -50, -65, 15, 24, -40, 
  -26, 51, -4, -31, 10, -15, 57, -54, -37, 87, 3, 127, 50, 17, -10, -16, -8, 40, -58, 58, 
  -72, -21, 6, 22, -4, 36, 35, 36, 72, 8, -10, 48, -19, 19, -51, 57, 56, -27, -21, 5, 
  -47, -52, 52, -20, 63, 84, -40, 1, 35, -33, 52, -15, -17, -18, -11, -13, -54, -56, -17, -54, 
  -55, -27, -51, 43, 24, -55, -42, -61, -8, 19, 42, -68, -62, 49, -15, -15, -25, 38, 12, -56, 
  -43, 70, 11, 60, 37, -49, 43, 25, 14, 21, -53, -46, -53, 80, 37, -44, 21, -44, 47, 13, 
  -62, -22, 9, 39, 17, -29, 15, -54, -22, -60, 68, -2, 49, -20, 31, -4, 30, 8, 23, -55, 
  -73, -64, 4, -28, -48, -89, -3, -53, -39, -3, 26, -34, 38, -34, -57, -14, -53, -37, -49, -24, 
  -40, -32, -44, 69, 78, -9, 16, 19, 41, -45, -61, -5, 6, -55, -31, 25, -25, 27, 41, 16, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0059016132727265358, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 2, 5, 5, -2, 10, 1, 3, 2, 4, -8, 3, -8, -11, 13, 7, -10, 12, -2, 7, 4, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 6.9900517701171339e-05, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*40] = { 
  32, -25, 29, -60, 41, 28, -38, -19, 18, 3, 30, 35, -13, -40, 127, -29, -41, -23, 39, -31, 10, 12, 81, -7, 88, 4, -29, 61, -15, -27, -9, -27, -31, 6, 38, 0, 12, 16, 5, -35, 
  50, -44, 70, 43, -51, 3, 41, -36, -38, 31, 44, -36, -7, -9, 8, -43, 6, -55, -17, -49, -27, 45, 3, 83, 4, -5, -41, -34, 8, -1, -23, 50, 57, -17, 46, -44, -10, 39, -40, -52, 
  -52, -41, 13, 40, 49, -58, -4, 32, 5, 10, 19, -35, -32, 28, 60, 8, 4, -6, 27, -47, -9, 65, 27, -10, 35, -16, 39, -39, -53, -22, 21, -22, -51, 67, 53, -22, -13, 38, -7, 46, 
  -11, -15, -6, 40, 67, 2, -47, -51, -33, 17, 0, -6, -42, 38, -48, 59, -40, 51, -39, -44, -30, 8, 80, -36, -49, 11, 45, -42, 41, -25, 19, -29, -72, -20, -39, 1, 33, -43, -29, -44, 
  24, -52, -12, -15, -54, 41, -23, 18, -44, 60, -34, -34, 4, -50, -10, -34, -2, 72, 22, 17, 43, -51, 62, 27, 34, 18, -65, 50, -55, 20, -50, -13, 41, 25, 19, 75, 11, -26, -21, -56, 
  -27, 23, 4, 23, -22, -29, -52, 5, 13, -56, 48, 56, -6, 36, -23, 83, -36, -49, -50, -47, -10, -16, -39, -28, 13, -18, -4, -37, -44, 18, 21, 29, 18, 37, -6, 1, 49, -42, 20, 42, 
  65, 38, 27, 65, 23, -48, 19, -15, -24, -16, -9, 35, 50, -1, -16, -33, -31, 57, 26, 4, -50, -1, -10, 1, -55, 31, -19, -41, 36, -19, 30, -42, -22, 7, -58, 30, -45, 30, -56, 2, 
  -1, 4, 19, 30, -33, 35, -40, -11, 9, -25, 23, 10, 8, 52, -17, -59, 89, -51, -40, -41, -34, 26, -26, -4, -25, -13, 18, 40, 4, 4, 25, -40, -33, -32, -1, 58, 44, -14, 15, -6, 
  71, -20, -26, 43, -42, 35, -3, -1, 5, -46, -5, -36, 71, 0, -17, -3, -17, 24, 9, 13, 35, -13, 0, 73, 5, 22, -37, 33, 9, 35, 5, -48, 64, -9, -16, -9, -51, -55, 0, -45, 
  -32, -13, 61, 4, 16, 64, 3, -62, -20, -43, -45, -18, -16, 47, -60, 3, -22, 13, -40, 10, -57, -34, -16, -43, 36, -49, 17, -16, 9, 47, -5, 19, -17, 3, -12, 32, -11, 60, 24, -22, 
  -36, 28, -3, -32, 24, 7, -26, -46, 16, 21, 21, 45, -20, -19, -29, -31, -21, -34, -56, -33, -37, 5, 71, -50, 14, 4, 12, -15, 33, 60, 17, -26, 38, 67, 10, -40, 55, -35, -42, 29, 
  -6, -24, -53, -51, 9, -61, 51, -28, -53, -5, 26, 7, -43, -37, -25, 28, -36, -7, -49, -29, -54, -40, 1, -59, -6, -32, -23, 29, -21, -8, -20, -55, 24, -43, 27, 34, -36, 53, -17, 16, 
  -32, 37, 126, -43, -26, -57, 52, 8, -6, -5, -12, 75, 59, -51, -32, 37, 26, 17, -39, 44, -31, -34, 49, -10, -15, 7, -32, 4, 65, -19, 101, 61, 63, -63, -37, -49, 44, 33, -61, -59, 
  -33, -23, -1, 34, -58, 45, -39, -50, 52, 41, -44, 35, 43, 4, -19, -25, 41, 77, 25, 51, -4, -38, -38, 18, 21, 18, -30, 16, -30, 72, -10, 89, -21, -38, -15, -2, -6, 63, 37, 26, 
  -34, 13, -8, -47, -34, -57, 49, -19, 37, 42, 26, 52, -46, 11, -5, 70, 58, -44, -53, -31, 23, -21, -31, 34, -35, 41, 21, -40, 60, 2, -25, 28, 8, -20, -32, -49, 11, 70, 66, -11, 
  12, -36, -40, -51, 41, -42, -35, -13, -59, 10, 54, -49, -46, -22, 118, -32, 21, 18, -22, 4, -27, 22, -41, -45, 32, 10, 0, 10, 9, -13, -57, -23, -20, 9, -58, 12, -40, -5, -58, 9, 
  16, 11, 12, 3, 0, 49, -41, -4, 35, 26, -54, -46, 43, 23, -19, -44, 30, 70, 7, 55, -55, 13, -24, -12, -27, 38, 57, 21, 62, 67, 7, 85, -25, 22, 53, -27, -12, 68, 16, 9, 
  -48, 19, 8, 45, 56, 39, 12, 4, -58, 45, 2, 47, -62, -31, 55, -18, -54, 7, -30, -37, 10, -40, -14, -43, 27, 42, 23, -35, -23, 38, 1, -15, -5, -3, 41, -5, 13, 30, 60, 42, 
  58, -50, 28, 43, -41, 8, 52, 13, -24, -23, -46, -53, 41, 5, 27, -17, -44, 20, 53, 23, -7, -43, -44, 71, -8, -11, 33, -2, 58, 63, 42, -14, 8, -11, 41, -38, -33, -10, -23, 27, 
  22, -54, 68, 95, -6, 30, -27, -45, 43, 3, -7, -49, -1, 51, 6, -66, 59, 1, -21, -54, 3, 60, -60, -20, 39, 7, 7, 30, 60, 64, 24, -47, -1, -12, 47, 31, 35, 65, 6, -40, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,40 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0050821159966289997, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[40] = { 7, -7, 4, 9, -5, 9, 15, -1, 14, -6, -2, 0, 10, -2, -12, 2, 5, 6, 10, 16, -12, -13, 6, 16, -3, -8, -9, 7, 17, 4, -19, 3, -7, 2, -3, -10, 3, 8, -8, -3, };
const TfArray<1, int> tensor_dimension7 = { 1, { 40 } };
const TfArray<1, float> quant7_scale = { 1, { 3.9050730265444145e-05, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[40*60] = { 
  25, 71, -11, 55, 6, 60, -80, -24, -51, -27, 28, 10, 34, -14, -10, 30, -15, -36, 28, 1, -68, 27, 13, -37, -72, -49, 24, 34, 111, -21, -36, 34, 56, -58, 14, -30, -46, 28, -50, -8, 88, 37, 48, -39, 15, -28, 13, 54, 52, -67, 3, -61, -72, 7, -56, -20, 52, -4, -38, -45, 
  -43, 26, -56, 28, -32, -13, 63, -37, -40, -31, 17, -58, 50, -29, 11, -13, 39, 36, 35, -38, 48, -9, -45, -23, 10, -64, -38, -17, -56, -16, -28, -15, -40, -43, 62, 53, 42, 6, 1, -10, 55, 10, 45, -52, 1, 45, 29, 6, 1, 28, 4, 53, -44, 11, 45, -64, -48, -45, 25, 20, 
  -8, -37, -18, 4, 79, -28, 77, 25, -6, -24, 23, 109, 69, 118, -42, -74, 9, -46, -12, -47, -27, 15, -28, 59, 40, -72, -53, 7, -41, -23, -47, 93, -59, -52, -47, -58, 61, -53, -47, 21, 29, 51, -67, -13, -74, 81, -29, 41, -19, -52, -1, -54, 46, -26, 20, -49, -11, 4, -14, 32, 
  62, -30, -17, -33, -9, 94, 16, 29, 64, -49, -45, -38, -23, -19, -22, -35, -45, -17, -30, -66, 94, 61, -33, 11, -55, -67, -7, 72, 39, 60, -50, 94, 92, -58, 78, -44, 50, 43, -26, -18, 71, -25, -23, -7, -31, 92, -54, 22, -21, 1, 68, -1, -44, -25, 29, -3, -13, 40, -19, -60, 
  -45, -32, -51, -7, -29, -54, -17, 39, -56, -33, -16, -31, 48, 57, -18, -53, -36, 18, 15, 101, -38, -6, -58, -28, -12, 42, 112, 5, -57, 60, -49, 23, -57, -3, -11, -53, 107, -60, -9, -72, -69, -41, 47, 11, 37, -23, 63, 33, 82, -12, 34, -26, 18, -76, -9, -39, -5, 39, -29, 83, 
  -40, -15, -67, -37, -26, -69, -26, 23, 4, -52, 32, -53, -10, -19, 39, 72, 43, 88, 4, 10, -58, -48, -17, 36, 6, -66, 5, -17, -55, 35, -46, 38, -46, 23, -14, -27, -57, 8, -54, 59, 16, 69, 22, 23, 24, 60, -49, 65, 100, 83, 45, -23, 30, 17, -50, -63, -65, 70, 34, -11, 
  37, 76, -15, -36, 50, -20, 51, -55, -3, 9, -20, 2, -52, 110, -64, -13, 29, -39, -14, 13, 32, -35, -64, -49, 39, -25, -18, -31, 24, -50, -65, 13, -41, -58, 35, -26, 97, 47, -7, 31, 100, 35, -3, -50, -58, 45, -78, 37, 97, -43, -30, 51, -61, -26, 21, 59, 10, -9, -18, 61, 
  -16, -27, 78, 34, 38, 13, 51, -64, 52, 22, 77, -66, 36, -23, 52, 66, -51, 50, -45, -25, 17, -51, 56, -17, 82, -26, -11, -40, 43, -33, -50, 18, 36, 2, 44, 4, 75, -16, -61, -63, -47, -38, -54, 53, 18, -2, 23, -37, 44, -4, 38, -6, 74, -5, -47, 51, -4, 18, 46, 46, 
  37, 88, -19, 7, -44, -3, 44, 57, 16, -3, -73, 87, 39, 13, 5, 45, -64, 65, 6, -76, 46, 46, -31, 17, 11, -68, 38, 8, 66, -37, -46, 66, -41, -4, 78, 13, -3, -24, 25, -45, -14, 91, -74, -29, -28, 45, -39, -31, -43, 13, 58, -63, -52, -36, 2, 58, 54, -54, -9, 5, 
  10, 53, 49, -35, -14, 86, 38, 3, -29, -2, 103, -66, -29, 75, -68, 17, -25, -61, 69, -28, -32, 77, 5, -13, -50, 3, 85, -2, -28, 69, -63, -18, -45, 16, -58, 51, -28, -9, -69, 49, 6, 30, -61, -56, 76, -2, 94, 48, 23, 2, 26, 88, -25, -17, 15, -15, 24, -42, -41, -20, 
  -40, -7, -32, 60, -37, -50, 32, 20, -52, 4, 25, -75, 34, 37, -29, -46, 5, -8, 39, 49, -33, 48, 6, 44, 42, 103, -9, -57, 18, -37, 9, 5, 18, -21, 18, -5, 110, -61, 67, -65, 44, 14, 20, -29, -6, -9, 75, -57, 48, 55, -28, -56, -10, -62, 97, -45, -25, -39, -12, 82, 
  -71, -31, 12, 6, 9, -37, 51, -48, -53, 60, 61, -15, 26, -25, 28, 10, -9, 22, -16, 45, 41, -18, -23, -50, -21, 98, -76, 39, 39, 51, 12, -69, -35, -30, -36, -40, 29, 65, 5, 48, -66, 33, 0, 9, 1, 61, -15, -37, 1, 1, -51, 24, 29, -15, -37, 3, -57, -75, 82, 42, 
  -53, -38, -2, -51, -51, 41, -31, 82, 33, 9, -45, 59, 28, 116, -14, -46, 9, 44, -45, -50, -39, -30, -18, -48, -5, 36, 5, 40, 6, -36, -21, 62, -40, -48, 34, 55, -24, -2, 63, -20, -44, 13, -43, 53, -26, -54, -8, -56, -48, 70, 47, -38, -59, 103, -18, -24, 48, 94, -64, -44, 
  3, 43, 28, -58, -32, 38, -59, 70, 40, 24, -19, 47, 9, 27, -60, 31, -32, 92, -42, -6, -65, 35, -51, -35, 14, -58, 34, -23, -22, 16, 23, -18, -50, 38, 16, -13, -41, -58, 31, 59, 22, 40, 31, 77, -44, 24, -39, 50, -20, 19, -55, 21, -76, -28, -83, 14, -78, -10, 0, -34, 
  12, 41, 3, 22, 41, -33, -62, -40, -11, -84, -41, -46, -17, -9, 2, -3, -35, -37, -20, 25, 6, 4, -48, -24, 30, 32, 54, -35, -26, -78, -54, -55, 30, 34, 17, -82, 34, 23, 7, 42, -66, 5, -68, 43, -57, 11, 24, 56, -24, -37, 27, -46, 12, 35, -14, 37, 35, -49, -31, -43, 
  49, -83, -21, 28, 27, 72, 57, -60, -67, 61, -27, 15, 5, 21, -3, 67, 46, -10, 58, -25, -36, -32, 87, -7, 43, 46, -12, -43, -45, 3, -27, -62, 58, -49, -12, 58, 85, 9, 90, -38, -2, 25, 35, -28, 94, 54, 64, -66, 11, -61, -52, -40, -9, -90, 95, -33, -56, 32, 6, 5, 
  29, 57, 9, -13, -2, -17, -2, 94, -41, -13, 38, 24, -64, 67, -62, -41, 78, 18, -14, -21, -9, 34, 49, 103, -8, 10, 23, 5, 24, -63, -24, 7, -61, 22, 13, 4, -46, -45, -70, -30, 54, 53, -22, -6, 63, -66, -29, 0, -29, 24, -64, 49, -13, -12, -26, 39, -47, 63, -55, -69, 
  50, 80, -28, -12, 2, 28, 38, -26, -47, 45, 21, -32, -15, -47, -27, -38, 18, 32, -83, -66, -63, -10, -47, 26, 8, 13, 59, 41, -65, -9, -72, -38, 3, -19, 25, -35, -38, -10, 46, 21, 2, 55, -18, 51, 49, -23, -14, 73, 81, 26, 53, 54, -31, 107, 25, -44, -59, 96, -51, -26, 
  27, 66, 2, -56, 59, -53, -61, -16, 7, 51, -44, 51, 84, -60, 52, 58, -58, 36, -29, 48, 16, -62, -53, 109, -3, -44, 11, -22, -49, -9, -66, 103, 94, -24, -12, -64, 23, 16, -51, 76, 25, 95, 42, 60, -3, -42, -55, -37, 10, 51, 71, 34, 41, -22, -41, -16, 23, -17, 16, -55, 
  -39, 73, -48, -22, 89, -67, -54, -63, -15, -9, 19, 87, 9, 15, -49, -27, 46, -3, 18, -44, -56, -16, -68, 43, -47, -61, 58, -62, 60, -39, 79, 41, -51, -2, -25, -28, 33, 49, -6, 7, 43, 75, -4, -10, -56, -17, -44, 57, -36, -50, -37, -49, -57, -1, 45, 39, 42, -11, 46, 1, 
  -32, 33, 10, 8, -50, 44, 39, 32, 45, 38, -36, -10, -60, -20, -51, 8, -29, -19, 53, -27, 71, 18, -19, -23, -19, -69, -83, 28, 65, -4, 35, 30, 32, 12, 27, 11, 18, -83, -17, 35, 57, 2, 41, 19, -55, -35, 5, 26, -17, -7, -65, 12, 41, -59, 24, -31, 31, -24, 50, 36, 
  15, -32, -54, 39, -41, -64, -25, 38, -6, 41, -7, 15, -70, -15, 51, 15, 23, -82, 14, -17, 24, 14, 41, 3, -53, 70, -44, 44, -62, 16, 53, -64, -62, 25, 46, -31, 19, 47, 42, -10, -22, 25, -3, 61, -25, -17, 18, -17, -18, 10, -36, 4, 49, -42, -46, -49, 14, -59, 80, 29, 
  -6, -25, 36, -12, -57, -4, -10, 5, 24, -55, 103, -71, -36, 59, 47, 81, 62, -60, 90, 25, -52, 102, 94, -21, 52, 30, 72, -15, -30, 86, -17, -49, -27, -3, -46, -22, 22, -31, -54, 23, 38, -53, 74, 63, 67, -14, 77, -37, 63, -27, -66, -4, -36, -21, 17, -39, -24, -44, 101, -33, 
  63, -32, 52, 1, 78, -45, 0, 68, 18, 15, -16, 25, 50, -36, -37, 2, -11, -44, -63, -30, 15, -57, -36, 78, -11, -38, 11, -50, 30, -21, 21, 88, -11, 50, 56, -68, -65, -2, 63, 31, 51, 38, -7, -23, -67, -9, -62, 61, 82, -26, -25, 35, 24, 83, -31, 81, 19, -13, -16, -26, 
  -64, -32, 57, 17, 24, 66, -14, 6, 36, 9, 99, -33, -42, 11, 5, -65, -52, 56, 102, 52, -46, 73, 73, -45, -36, 109, -54, -27, -51, -64, -6, 41, 22, 49, 74, -10, 85, -7, 41, -37, -38, 37, 41, -77, 80, 43, -31, 0, -8, 61, -21, 27, -36, -64, 17, 21, 32, -38, -43, 83, 
  -56, 9, 19, -15, -38, 6, -15, -64, 44, -19, -52, -43, 67, 40, 0, -52, 22, -4, -2, -36, -29, -6, -3, 2, -19, -65, -47, -21, -27, 5, -68, 82, -25, -20, -18, -27, -54, -28, 9, -51, 44, -23, -14, 33, -67, -69, -50, 8, -21, 38, 57, 42, 4, 4, -4, 34, -57, -60, -86, -41, 
  -45, 4, 13, 0, -12, -15, -39, -28, 17, 35, -29, 39, 31, 3, -28, -56, 85, 65, -61, 21, 22, -68, -56, 91, 23, -16, -43, -63, -60, -32, 13, 9, 41, -26, 13, -34, -31, 38, 15, -8, 7, 19, -61, 12, 45, 23, -59, -18, -40, -76, -6, -16, 18, 21, 0, -17, -5, -63, -55, 24, 
  38, 92, -31, -55, 22, -49, -39, 10, -53, 32, 22, -34, -62, -57, -49, 46, -40, -13, 11, 8, 70, 15, 9, 17, -24, -44, -43, -21, 42, 24, 62, 45, -22, -45, -36, -39, 2, 47, -58, -32, -32, 58, 43, 96, 36, 18, -86, 39, 15, -2, 69, 73, -2, 61, -37, -49, 10, 19, -61, 67, 
  44, -58, 86, -16, -15, 8, 21, -29, -61, -60, -35, 108, 41, 16, 3, 11, 56, 106, -26, -39, -77, 14, -28, 51, -12, -32, 52, -14, -23, 28, -26, 53, -31, 62, 52, -38, -8, -53, -59, -48, -57, 2, -66, 21, -31, 15, -77, 64, 11, -43, 117, 74, -66, -51, 33, -14, -16, 7, 42, 56, 
  1, -2, -39, 57, -1, -62, -40, 61, -47, -30, -14, 6, 2, 16, -59, 49, -65, -67, 3, 7, 69, -12, 17, 70, -47, 7, -30, 57, 53, -24, -43, 40, 70, -40, 14, 31, -31, -26, -36, 58, -22, -66, -65, 25, 50, -52, -69, 13, -17, 52, -42, 65, 39, -50, -52, -17, -17, 65, -15, -61, 
  -10, -47, -9, -57, 60, -10, 57, 89, -44, -57, -34, 61, -67, -43, 45, -9, 66, 3, -76, -30, -69, -74, -55, -50, -68, -44, 12, -64, 43, -73, 55, 5, -5, -46, -63, -42, -27, -25, -1, 85, 15, 42, -74, 40, 13, 88, -72, -16, -24, 37, -19, -5, -47, -44, 23, -67, 34, -29, -70, 37, 
  60, -67, -28, 75, -22, 26, -47, -13, -18, -1, 16, -29, 21, 14, -45, 39, -5, -18, -39, -67, -58, -17, 10, 50, -53, -43, 63, 15, 40, -35, 16, 21, -46, -70, 38, 49, 29, 31, -57, -15, -28, -45, -28, -20, 4, 65, -23, 13, -13, -1, -15, 31, -35, 44, -9, -55, -32, 9, 73, 61, 
  95, -7, 22, -47, -44, -73, 31, 20, 80, 38, 43, -59, -49, -5, 10, -5, 53, -10, -63, -65, -40, 50, 27, -38, -16, 35, -12, -47, 30, -15, -58, -50, -37, -70, 63, 42, 36, -37, -8, -37, 68, -40, -64, -12, 61, 2, -67, 0, 86, -63, -37, -67, -6, -14, -22, -26, -59, -11, 4, -65, 
  -7, -39, 25, -23, 33, -13, 29, 46, -8, 8, -17, 32, -4, 61, 28, -45, -27, -27, -1, 92, 77, -37, -33, -19, 33, 37, 13, 68, -21, 89, -40, -15, -10, 18, -47, -62, 32, 61, -58, -32, 38, -9, 67, -10, 20, -25, 56, -38, -61, 45, 65, -26, 97, -59, 26, -58, 57, 44, 92, -24, 
  -11, -8, 53, -56, 51, -42, 37, 30, 64, 15, -9, 44, -34, 63, -4, 54, 95, 5, -36, -21, -45, 69, 93, -23, 52, -55, -7, -42, 101, -37, 49, -51, -58, -24, -12, 10, 58, 71, 62, -50, 30, 52, 41, 59, -67, 87, 39, -50, 26, 56, 64, 80, -25, 68, 55, 4, 10, -24, -36, -54, 
  35, 29, 48, -44, -7, -5, 19, 20, 40, 83, 11, -71, -20, -73, 30, -51, 43, -72, 108, -41, 54, -44, -11, -17, 20, 23, -54, 12, -17, 57, -27, -63, 50, 12, 50, 75, -39, 39, 28, 52, -12, -19, 7, 19, 81, 33, -20, 21, 20, 75, 17, 39, 107, -24, -3, 10, -37, -78, 6, -30, 
  -57, -29, 17, -5, -37, -51, 75, 21, -17, -47, 40, 18, -13, -26, 83, -23, -2, 0, 21, -69, -9, -22, 20, 5, -27, 127, -21, -35, -55, -29, 63, 9, 54, 25, 27, 41, -15, 6, -38, -10, -69, -40, 82, -26, -20, 10, 27, -13, 44, 67, -17, -35, -32, -57, 3, -61, 71, -28, 13, 62, 
  24, -58, 83, 55, 73, -41, 55, 2, -45, -19, -22, -6, -58, -69, 17, 36, -1, 35, -29, 54, -79, -64, 27, 40, -10, -46, 69, 28, 5, -56, 55, 7, -39, -2, 54, -49, -61, 104, -49, -51, 40, 46, -5, 49, 6, -70, -67, 49, -56, -31, -53, 35, 36, -2, -9, -4, -18, -32, -39, 10, 
  82, -38, 57, 27, -38, 4, -77, 93, -48, 23, -42, 44, 50, 4, 84, 2, 62, -22, 56, 35, -53, -12, 10, -24, -13, -20, 32, 62, 8, -38, -43, -81, -66, -45, -68, 40, 37, 7, -56, -75, -5, 73, 47, 24, 0, -63, -42, -81, -33, 0, -55, -15, 48, -39, -42, 38, -24, 31, 58, 3, 
  -12, -6, 23, -15, 23, 19, 7, -64, 60, 66, -63, 40, -25, 36, 55, 52, -15, 19, 89, -2, 2, 65, -41, 43, -48, 102, -5, 2, 47, 7, 45, 8, 3, 65, -65, 12, -37, 60, 21, 19, -21, -13, 78, -62, 13, 0, -5, 15, 4, 80, -76, -11, -19, 11, -9, 58, 25, 53, 13, 7, 
};
const TfArray<2, int> tensor_dimension8 = { 2, { 40,60 } };
const TfArray<1, float> quant8_scale = { 1, { 0.0032054700423032045, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[60] = { 2, 6, -4, -5, 0, -10, 4, 0, -5, -8, -1, 5, -5, 1, -4, -5, -11, -2, 5, 3, 1, -2, 1, 2, -4, 5, 6, -4, 2, 2, -3, 5, -6, -2, 1, -3, 1, -3, -4, 1, 2, 1, 7, 3, -3, -3, 3, 6, 4, -2, 3, 0, -6, 4, 2, 4, -6, 1, 2, -1, };
const TfArray<1, int> tensor_dimension9 = { 1, { 60 } };
const TfArray<1, float> quant9_scale = { 1, { 7.2645168984308839e-05, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[60*18] = { 
  7, 94, -5, -22, -47, 69, -22, -4, -83, -1, -7, -55, -52, -52, -50, 54, -66, -72, 
  -42, 49, -4, 101, 10, -2, 117, -5, 50, 83, -10, 61, -56, -7, 80, -22, -4, -10, 
  22, -58, 15, -25, -33, 29, -24, -60, -7, 26, -25, -57, -40, -8, -66, -15, 23, -4, 
  -57, 26, 13, -72, -4, -30, -1, -11, 47, -7, -35, -25, 20, 6, -22, -62, 46, -16, 
  67, -22, 73, 65, -18, 52, 25, 36, -27, 48, 28, -24, -16, 27, -65, -41, 16, 27, 
  -11, -11, -15, 38, -60, 21, -28, -35, 20, 6, 1, -49, 47, 72, -10, -52, -10, -13, 
  14, -57, -12, -17, 20, -19, 32, 32, -3, -66, 42, -9, -51, 40, 7, -89, 1, 73, 
  45, 42, 16, 70, -35, -73, -55, -36, 24, 23, -2, -62, -12, -5, 86, 17, -35, -3, 
  37, -28, 3, -22, 15, -39, 32, 80, -2, -28, 33, -32, -53, -2, -47, 14, -17, -53, 
  -33, -5, -69, -56, -54, 44, 38, 29, 42, 16, -17, 1, 51, 52, -16, -74, 31, 47, 
  57, -71, 45, -12, 2, -40, 3, 41, 18, -21, -63, -8, -29, 6, -8, 73, 59, -45, 
  -12, 19, 42, -10, 71, 50, 99, -1, 28, 82, 6, -36, -31, 43, 62, -20, -27, 83, 
  -42, -15, -30, 61, 6, 44, 63, 29, 12, -14, -6, 52, 49, -40, -51, 4, -40, -46, 
  -12, -35, -57, -16, 32, -70, -74, -49, 0, 31, -7, -44, 21, -9, 17, -23, 60, 29, 
  36, -15, -6, -16, -63, -49, 40, 58, -43, -84, 57, 62, -50, -33, -66, 17, -46, 43, 
  0, -38, -16, 28, -13, 59, 41, 28, 34, -8, 11, 43, -1, 68, 24, -21, -41, 0, 
  1, -7, -19, -42, 15, 22, 34, -53, -5, 14, -8, -50, 5, -8, -9, -46, 8, -6, 
  -11, 53, -44, -6, 0, -6, 118, -12, -31, 66, -10, 20, 80, -22, 52, -15, -49, -56, 
  -42, -92, -35, -42, -68, -52, -51, 24, -4, -43, 3, -43, -11, -7, -46, -21, -21, -45, 
  -35, -59, 52, 11, 21, -58, -40, -52, -9, -40, -43, -10, -42, -25, 41, -68, -2, 7, 
  -14, -3, -44, -18, -59, 5, -38, 63, 11, -66, 17, -43, 45, -6, -22, -63, -34, 24, 
  -6, -40, 39, -56, -2, 39, -42, 40, 12, -36, 38, 24, -41, -21, 12, 33, 10, 13, 
  -8, 2, 49, -75, -1, 6, -5, 33, -11, -75, 38, -2, -26, 10, -18, -42, -8, -5, 
  76, 19, 90, 72, 62, -27, 72, -62, 72, 84, 27, 61, -70, -22, 49, 2, 17, -2, 
  6, -37, -4, -12, -13, 35, -19, -17, 3, -49, -19, -25, -43, 25, -29, 53, 39, -40, 
  12, -57, 39, -92, 12, -84, -21, -2, 0, -70, -19, 27, -28, 6, -26, -57, 51, 15, 
  -3, -14, 44, 8, 68, 14, 90, -42, -10, 104, -69, -40, 51, 43, 11, 38, -8, -42, 
  -60, 37, 3, -9, 22, -19, 73, -3, 82, -40, 38, -10, 10, -2, 78, 32, 15, -5, 
  86, -39, -25, 5, -28, 52, -1, 33, 32, 71, -64, -62, 56, -39, -12, -22, 31, 70, 
  10, -63, 7, -66, -25, -37, -56, -3, 8, -25, -19, 52, 25, -12, 0, 62, -42, -57, 
  39, -36, 34, -55, -49, 5, 23, -39, 7, 16, -15, 57, -50, 33, -12, -12, 62, 28, 
  35, -21, -27, 48, 102, -11, 12, 87, 61, 101, -4, -8, 33, 55, -18, 35, -36, 29, 
  -78, 13, -41, -14, 12, -11, -12, -27, 10, 28, -5, 28, -29, -13, -26, 81, 19, -74, 
  -57, 72, 50, 6, 6, -49, -26, -15, -46, -20, -54, -16, 8, 84, -30, 18, 76, -33, 
  -38, 48, 5, 76, 89, -29, -48, -19, -43, 97, -28, -24, 20, -63, 35, -4, -41, 70, 
  41, -84, 8, -40, -6, -4, 28, -8, -4, -40, -20, -8, -45, 4, -48, -30, 32, 41, 
  -64, 26, -15, -65, 13, -77, -34, -17, 30, -66, 1, 8, -51, -1, 18, 28, -2, -12, 
  -7, 33, 23, -47, 28, -52, -7, -58, -23, -21, -61, 42, -7, -37, -33, -5, 71, 60, 
  -4, 51, -22, -45, -14, 21, 49, -10, -70, -44, -26, 48, -12, -39, 35, 56, -46, 42, 
  56, 13, -32, -36, 8, 7, 29, 97, -9, 73, -8, 17, 32, -34, 67, -14, -22, -47, 
  1, 57, 11, 46, -1, 58, 79, 36, -46, -53, 66, 14, -20, -25, -64, 27, -1, 1, 
  69, 47, 23, 78, 84, 41, -9, -13, -6, -30, 68, -18, 32, -40, 37, -6, -43, -4, 
  -60, -54, 40, -24, -44, 9, 34, -42, 52, -83, 10, -2, 33, 0, 2, -74, 44, 7, 
  -21, 51, 29, 91, 21, -18, -35, -6, -70, 64, 71, 39, -12, 95, 59, -37, -34, -57, 
  6, -70, 0, -17, -53, 22, -29, -19, 32, -55, 29, -11, -9, 42, 18, 26, 25, 1, 
  10, -60, -47, -28, 10, 8, -59, 15, -9, 44, 38, -31, -12, 3, 7, -73, 62, -15, 
  -29, -100, -9, -11, 11, -57, -47, 40, 26, -18, 7, 19, -59, 21, -19, -35, -20, 18, 
  26, 52, -26, 122, -29, -9, 82, -15, -18, 1, 8, -68, 41, 44, 20, -27, -25, 0, 
  27, 43, -19, 53, 7, -37, 50, 9, 27, -66, -26, -16, -36, -27, -62, -1, -56, -45, 
  -78, 12, -37, -69, -46, 3, -26, 41, -6, 11, -24, 54, -1, 28, -37, 37, 66, -31, 
  33, 6, -16, 16, 54, -10, -58, 57, -41, 83, -65, 83, -30, -28, -24, -12, -40, -25, 
  109, -34, 45, 64, 2, 0, -16, -21, 55, 56, 6, 9, 20, 96, -12, 26, -41, 36, 
  1, -42, -45, -41, -7, -11, 17, 12, -3, -4, -48, 5, -30, -1, -60, 21, 10, -5, 
  -11, 78, -8, 49, 4, 27, -24, 17, -90, 37, -61, 8, 81, 54, 87, 44, 8, -32, 
  -23, -55, 21, -68, -53, 18, 46, 53, -1, -27, -52, -15, 55, 5, -33, -38, 6, 21, 
  -33, 56, 34, 80, 65, 33, -42, 2, -7, -19, 8, -17, 13, -34, 68, 4, 32, 76, 
  -28, -14, 46, 5, 2, -25, -49, 5, 3, 38, 80, -46, -6, -17, -5, -35, 5, -50, 
  76, 14, -6, 78, -27, 31, 17, 60, -22, -24, -23, 127, 72, -22, -6, 108, -42, 29, 
  15, -8, -8, -37, -68, -40, -40, 38, 21, -58, -16, 82, -37, 34, -25, 12, 51, -24, 
  -23, -46, 57, 21, -23, -83, -26, -57, -9, 24, 45, 24, -1, -45, -1, 29, 28, 0, 
};
const TfArray<2, int> tensor_dimension10 = { 2, { 60,18 } };
const TfArray<1, float> quant10_scale = { 1, { 0.0039713890291750431, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension11 = { 2, { 1,60 } };
const TfArray<1, float> quant11_scale = { 1, { 0.012182528153061867, } };
const TfArray<1, int> quant11_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&quant11_zero, 0 };
const TfArray<2, int> tensor_dimension12 = { 2, { 1,40 } };
const TfArray<1, float> quant12_scale = { 1, { 0.013754215091466904, } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension13 = { 2, { 1,20 } };
const TfArray<1, float> quant13_scale = { 1, { 0.018466869369149208, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension14 = { 2, { 1,10 } };
const TfArray<1, float> quant14_scale = { 1, { 0.016378026455640793, } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension15 = { 2, { 1,2 } };
const TfArray<1, float> quant15_scale = { 1, { 0.021006073802709579, } };
const TfArray<1, int> quant15_zero = { 1, { 78 } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&quant15_zero, 0 };
const TfArray<1, float> quant16_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,10,9 } };
const TfArray<1, int> outputs0 = { 1, { 11 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 11,8,7 } };
const TfArray<1, int> outputs1 = { 1, { 12 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 12,6,5 } };
const TfArray<1, int> outputs2 = { 1, { 13 } };
const TfLiteFullyConnectedParams opdata3 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs3 = { 3, { 13,4,3 } };
const TfArray<1, int> outputs3 = { 1, { 14 } };
const TfLiteFullyConnectedParams opdata4 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs4 = { 3, { 14,2,1 } };
const TfArray<1, int> outputs4 = { 1, { 15 } };
const TfLiteSoftmaxParams opdata5 = { 1 };
const TfArray<1, int> inputs5 = { 1, { 15 } };
const TfArray<1, int> outputs5 = { 1, { 16 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension0, 18, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 160, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 2400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 240, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 1080, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension11, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension12, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension13, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension14, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension15, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension15, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[6] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[6] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 17, };
const size_t tflNodes_subgraph_index[] = {0, 6, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  16, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1096455_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 17;
  for (size_t i = 0; i < 17; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1096455_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1096455_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1096455_5_invoke() {
  for (size_t i = 0; i < 6; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1096455_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
