/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 25.08.2026 10:16:26

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1584;
#else
constexpr int kTensorArenaSize = 560;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,18 } };
const TfArray<1, float> quant0_scale = { 1, { 0.018234860152006149, } };
const TfArray<1, int> quant0_zero = { 1, { 31 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { 1, 0, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 3.0088547646300867e-05, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  -9, -92, 107, -88, 57, -28, -111, -64, -90, -104, 
  -127, -38, 45, -58, -58, 33, 57, 18, -21, -87, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0056873499415814877, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 3.2583437132416293e-05, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  -42, 91, 79, -64, 112, 64, -74, -84, -84, -101, 110, -36, -106, -14, 106, 94, -41, 93, -78, -101, 
  -65, 64, -23, 10, 15, 28, -39, 83, -3, -31, 86, -106, 62, 55, 3, -87, -106, 56, 53, -51, 
  -44, 89, 4, -39, 14, -62, 78, -85, -58, 92, -4, 127, 81, 43, -21, -10, 16, 54, -84, 115, 
  -108, -34, 21, 13, -14, 78, 57, 68, 89, 36, -8, 102, -34, 16, -72, 79, 62, -28, -36, 0, 
  -67, -90, 75, -4, 92, 105, -68, -2, 79, -66, 59, -42, -15, -17, -31, -47, -75, -80, -1, -77, 
  -98, -29, -79, 19, 18, -60, -90, -89, -27, 58, 75, -99, -107, 64, 8, -32, -52, 84, 9, -86, 
  -52, 88, 22, 73, 49, -89, 73, 53, 24, 37, -89, -86, -83, 99, 78, -95, 32, -71, 72, 22, 
  -85, -41, 33, 0, 19, -44, 14, -59, -43, -106, 85, 7, 54, -37, 79, 12, 29, 32, 25, -92, 
  -99, -106, 64, -62, -61, -98, 36, -22, -51, 69, 90, -17, 96, -43, -32, 14, -53, -4, -36, -23, 
  -60, -46, -68, 83, 65, -14, 3, 33, 20, -77, -105, -14, 12, -88, -47, 4, -44, 34, 34, 12, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0040245009586215019, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 3.469948933343403e-05, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*40] = { 
  48, -61, 38, -65, 24, 34, -45, -24, 11, 3, 20, 41, -10, -57, 78, -39, -64, -20, 65, -58, -9, -8, 67, 12, 79, 8, -57, 73, -9, -35, -18, -32, -44, 2, 51, 14, -4, 18, -1, -51, 
  39, -58, 54, 36, -55, -4, 17, -49, -50, 33, 67, -47, -43, -5, 16, -55, 1, -67, -23, -53, -22, 61, 24, 70, 4, -8, -48, -37, -2, -23, -28, 50, 70, -19, 46, -65, -7, 53, -66, -73, 
  -60, -59, 31, 65, 78, -72, 6, 44, 5, 7, 16, -60, -46, 50, 58, -5, 7, -9, 52, -71, -11, 67, 29, 3, 40, -47, 67, -46, -75, -30, 40, -29, -77, 73, 68, -25, -6, 56, -18, 58, 
  6, -36, -14, 49, 48, -41, -51, -50, -31, 20, 2, 4, -69, -5, -45, 66, -24, 49, -44, -61, -23, 36, 51, -39, -46, -5, 32, -62, 42, -27, 56, -32, -74, -26, -47, 16, 61, -64, -48, -59, 
  43, -75, 3, -13, -62, 64, -27, 19, -55, 60, -49, -64, 7, -58, -23, -51, 8, 75, 46, 53, 51, -64, 71, 50, 45, 8, -75, 69, -64, 35, -51, -21, 38, 30, 32, 78, 27, -15, -30, -73, 
  -12, 9, 17, 47, -10, -32, -65, 12, 22, -75, 60, 53, 1, 74, -50, 77, -30, -64, -58, -56, -13, -16, -45, -12, 25, -61, 7, -36, -46, 44, 41, 67, 8, 43, 7, 2, 72, -49, 22, 64, 
  63, 65, 35, 70, 38, -66, 35, -6, -20, -17, -5, 65, 59, -3, 1, -25, -31, 51, 27, 25, -69, 5, 11, 2, -65, 43, -14, -39, 50, -26, 43, -48, -26, 26, -76, 38, -74, 73, -74, 7, 
  -16, 48, 25, 9, -46, 51, -64, 8, 22, -36, 45, 0, -14, 59, 24, -64, 61, -78, -61, -35, -26, 36, -17, -20, -23, 4, 33, 54, 2, -15, 14, -75, -54, -32, -6, 68, 51, -26, 28, -10, 
  72, -18, -32, 36, -54, 37, -5, 3, 12, -59, 8, -48, 73, -4, -12, 11, -18, 22, 11, 42, 61, -10, 16, 72, 22, 26, -52, 41, 19, 37, 3, -64, 71, -3, -18, -16, -73, -63, -1, -59, 
  -60, 15, 45, 13, 9, 61, 21, -72, -23, -53, -57, 18, -2, 67, -54, 38, -41, 36, -54, 8, -57, -53, -7, -71, 73, -68, 47, -5, 16, 75, -17, -15, -25, 21, -4, 69, -5, 70, 49, -2, 
  -48, 40, 13, -29, 29, 11, -39, -61, 21, 7, 5, 49, -24, -14, -46, -42, -24, -43, -72, -54, -53, 10, 77, -65, 14, -16, 38, -20, 47, 76, 40, -47, 34, 76, 23, -49, 76, -40, -50, 41, 
  2, -19, -74, -57, 50, -73, 70, -24, -73, 10, 62, 24, -59, -35, -23, 14, -35, 17, -53, -35, -64, -28, 3, -69, 19, -69, -17, 73, -30, 13, 2, -64, 10, -39, 64, 58, -22, 64, -14, 46, 
  -19, 83, 127, -46, 83, -70, 78, 5, -3, 34, -13, 51, 97, -64, -12, 41, 41, 33, -50, 13, -51, -1, 107, -8, 0, -7, -40, 7, 49, -53, 62, 93, 97, -71, -39, -51, 64, 36, -39, -71, 
  -71, -30, -13, 21, -74, 31, -52, -66, 63, 44, -54, 51, 41, -17, -21, -20, 18, 64, 19, 63, -1, -52, -40, -3, 37, 20, -57, 6, -39, 47, -26, 70, -30, -48, -24, -7, -5, 61, 29, 21, 
  -64, 38, 10, -73, -41, -72, 42, -11, 55, 48, 22, 43, -57, 30, 32, 73, 58, -57, -67, -5, 50, -25, -38, 48, -39, 44, 58, -42, 71, 16, -11, -7, 7, -20, -50, -68, 13, 71, 48, -20, 
  34, -61, -41, -60, 20, -50, -30, -4, -60, 28, 31, -59, -22, -15, 52, -52, 62, 46, 5, -29, -54, 63, -68, -22, 30, 8, 12, 53, 31, -22, -54, -44, -22, 13, -44, 57, -52, 45, -71, 35, 
  4, 31, 4, -4, 5, 46, -52, -5, 49, 41, -67, -56, 36, 12, -7, -44, 24, 66, 2, 72, -72, 19, -18, -34, -29, 44, 43, 24, 53, 64, -3, 71, -36, 40, 55, -45, -23, 71, 15, 10, 
  -56, 11, 23, 76, 64, 65, 26, 11, -75, 64, -7, 61, -70, -25, 42, -27, -62, 30, -25, -50, 13, -51, -21, -30, 35, 40, 50, -37, -13, 67, 20, -11, -2, 2, 81, 10, 24, 65, 84, 73, 
  51, -50, 28, 44, -51, 8, 54, 27, -30, -27, -57, -70, 44, 1, 67, -2, -64, 24, 61, 40, 6, -53, -41, 64, 5, -30, 41, -2, 61, 62, 46, -35, 13, 1, 54, -55, -47, -16, -32, 39, 
  20, -71, 59, 70, 4, 44, -33, -59, 37, 16, 18, -69, -9, 53, 31, -75, 76, 10, -39, -73, 18, 77, -67, -39, 63, 5, 1, 25, 73, 62, 20, -61, 8, -1, 51, 19, 49, 69, 17, -51, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,40 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0040436312556266785, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[40] = { 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 1, 0, 0, 0, 0, };
const TfArray<1, int> tensor_dimension7 = { 1, { 40 } };
const TfArray<1, float> quant7_scale = { 1, { 2.6893563699559309e-05, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[40*60] = { 
  34, 89, -9, 65, -2, 83, -101, -54, -93, -28, 45, -7, -13, -9, -3, 63, -25, -65, 89, 39, -100, 51, 19, -62, -96, -55, 17, 20, 107, -27, -50, 13, 60, -100, 35, -32, -63, 21, -77, -15, 54, 31, 74, -64, 40, -26, 72, 59, 21, -105, 0, -96, -97, -26, -66, -37, 108, -20, -46, -47, 
  -59, 47, -88, 55, -49, 0, 100, -67, -60, -45, 40, -81, 91, -35, 28, -6, 78, 72, 78, -72, 76, 3, -76, -30, 45, -98, -58, -16, -100, 6, -15, -12, -60, -59, 99, 96, 94, 22, 32, -2, 97, 16, 88, -86, 17, 90, 55, 10, 1, 64, 28, 97, -41, 37, 79, -108, -56, -67, 67, 40, 
  -20, -47, -38, -21, 74, -45, 99, -5, -36, -33, 74, 83, 93, 87, -57, -95, -20, -94, 14, -36, -24, 55, -46, 53, 86, -97, -70, -18, -84, -10, -61, 89, -92, -101, -76, -103, 91, -91, -76, 6, 33, 54, -83, -42, -105, 79, 2, 30, -51, -87, 18, -86, 102, -61, 59, -67, -11, 20, 7, 49, 
  47, -60, -28, -66, -27, 99, 29, -13, 44, -80, -67, -83, -79, -46, -51, -60, -85, -36, -47, -103, 77, 63, -46, 0, -71, -106, -23, 86, 33, 56, -93, 79, 80, -87, 76, -76, 73, 32, -49, -49, 46, -55, -42, -51, -49, 100, -78, 0, -81, -31, 24, -21, -67, -77, 45, -33, -24, 15, -23, -82, 
  -39, -77, -84, -16, -44, -91, -20, 71, -87, -55, -47, -29, 114, 84, -11, -69, -32, 77, 0, 96, -43, 3, -103, -58, -13, 23, 107, 5, -85, 83, -85, 44, -97, -20, -56, -90, 126, -98, -2, -72, -102, -12, 76, 15, 104, -26, 58, 81, 120, -17, 85, -59, 24, -103, -24, -44, -24, 87, -61, 41, 
  -82, -36, -108, -50, -36, -107, -35, 11, -1, -74, 79, -96, -51, -41, 46, 100, 44, 56, 44, 49, -90, -81, -20, 21, 21, -78, 31, -44, -79, 63, -83, 36, -89, 47, 6, -38, -76, 12, -101, 45, -19, 53, 33, -7, 28, 73, -46, 43, 91, 87, 25, -22, 73, -28, -56, -94, -90, 56, 72, 10, 
  80, 77, -31, -65, 47, -14, 54, -106, -20, 3, -30, -44, -69, 81, -107, -1, 31, -46, 13, 27, 56, -34, -82, -69, 61, -10, -27, -50, -15, -38, -86, -21, -74, -92, -6, -52, 102, 55, -27, 70, 94, 38, -4, -104, -78, 52, -103, 38, 71, -69, -60, 76, -107, -51, 49, 49, 16, -18, -24, 78, 
  -17, -15, 100, 66, 80, 10, 62, -87, 93, 27, 91, -65, 65, -21, 80, 99, -88, 94, -78, -46, 21, -75, 89, -1, 89, -52, -1, -58, 82, -55, -81, 51, 38, -7, 85, -3, 99, -11, -90, -97, -54, -47, -97, 98, 20, -2, 18, -45, 78, -10, 78, 8, 74, 16, -90, 95, -7, 52, 58, 58, 
  50, 75, -32, -6, -84, 17, 97, 18, 12, 13, -108, 57, 62, -11, -4, 89, -92, 44, 54, -99, 79, 55, -33, -8, 57, -81, 49, -4, 67, -50, -59, 37, -77, -4, 79, 37, -4, -58, 36, -96, -42, 93, -100, -70, -34, 76, -24, -54, -90, 15, 68, -109, -62, -99, 32, 48, 96, -111, 6, 12, 
  59, 77, 81, -77, -21, 111, 39, 49, -28, -5, 114, -105, -11, 87, -78, 48, -52, -84, 73, -72, -34, 102, 12, -5, -62, -32, 41, 27, -58, 85, -107, -43, -58, 13, -92, 54, -45, -11, -101, 99, 62, 114, -97, -71, 125, -16, 95, 100, 73, 25, 63, 93, -36, 6, 20, -35, 31, -37, -43, -26, 
  -70, 22, -46, 118, -24, -87, 35, 57, -72, 6, 35, -87, 85, 115, -41, -66, 38, 25, 30, 48, -37, 74, 11, 117, 37, 70, 6, -99, 79, -63, -15, 59, 47, -29, 44, -12, 107, -96, 49, -74, 104, 56, 12, -11, -2, 19, 44, -72, 89, 81, -32, -83, -61, -60, 113, -52, -39, -38, -52, 113, 
  -104, -36, 23, 23, 38, -53, 44, -40, -89, 59, 90, 5, 46, -9, 26, 9, 4, 66, -39, 59, 66, -34, -39, -41, -36, 91, -107, 63, 73, 88, 13, -92, -55, -53, -50, -70, 14, 113, -3, 76, -100, 91, 16, 54, -2, 99, -65, -32, 14, -1, -69, 86, 6, 10, -65, 21, -83, -100, 95, 88, 
  -90, -55, -13, -79, -89, 66, -36, 72, 47, 23, -69, 50, 15, 103, -24, -92, 1, 41, -53, -59, -54, -59, -3, -67, 5, 96, -23, 102, -17, -48, -22, 37, -73, -63, 14, 81, -13, -5, 91, -50, -73, 4, -48, 31, -44, -91, 5, -100, -79, 82, 1, -62, -96, 35, -29, -77, 91, 71, -89, -45, 
  3, 65, 61, -88, -51, 75, -81, 44, 69, 64, 1, 48, 7, 20, -100, 72, -59, 85, -19, 19, -110, 75, -65, -77, 66, -56, 81, -35, -33, 53, 62, -27, -75, 91, 31, -4, -33, -109, 75, 82, 28, 35, 65, 80, -60, 35, -22, 49, -36, 47, -111, 53, -85, -65, -104, 21, -106, -10, 31, -38, 
  47, 56, 52, 39, 89, -10, -77, -69, 12, -86, -52, -97, 2, -22, 33, 22, -74, -71, 20, 73, 16, 36, -88, -62, 94, 100, 67, -64, -19, -97, -45, -112, 54, 78, 46, -102, 90, 74, 59, 86, -111, 8, -108, 52, -64, 39, 95, 91, -41, -40, 75, -62, 91, 49, 14, 68, 93, -59, -4, -70, 
  76, -107, -42, 72, 63, 96, 46, -66, -101, 50, -46, 85, -5, 70, -13, 79, 87, 17, 64, -61, -41, -47, 127, 20, 25, 43, 22, -62, -63, -1, -55, -75, 98, -56, 3, 54, 113, 19, 117, -47, 10, 64, 46, 5, 102, 89, 26, -72, 20, -87, -87, -41, -54, -102, 117, -35, -76, 63, -7, 16, 
  40, 69, -1, -39, -17, -29, 31, 71, -52, -19, 96, -14, -104, 59, -87, -54, 81, 10, 28, -5, -16, 61, 78, 96, 13, 58, 38, 4, 12, -74, -36, 2, -90, 56, 29, 14, -44, -74, -96, -26, 66, 53, -27, -18, 96, -99, 9, -12, -35, 48, -103, 65, 13, -50, -19, 27, -48, 80, -57, -92, 
  78, 74, -32, -32, -1, 48, 82, -45, -72, 83, 56, -76, -50, -73, -34, -62, 16, 3, -99, -87, -94, 0, -53, 16, 47, 72, 70, 70, -110, -7, -103, -77, 3, -21, 44, -39, -31, -11, 84, 29, -15, 63, -13, 44, 97, -32, 7, 65, 79, 35, 42, 69, -14, 84, 66, -74, -74, 93, -52, -9, 
  33, 26, 9, -97, 63, -90, -84, -43, 5, 96, -53, 20, 73, -96, 73, 85, -97, -5, -24, 71, 29, -89, -77, 85, 26, -43, -11, -39, -75, -1, -99, 96, 101, -43, -28, -95, 46, 16, -85, 90, 0, 106, 63, 41, 17, -50, -63, -81, -18, 60, 59, 23, 100, -70, -49, -29, 40, -51, 57, -87, 
  -68, 83, -90, -56, 75, -106, -73, -88, -31, -35, 42, 56, -22, 8, -71, -54, 26, -17, 74, -46, -81, -25, -102, 27, -85, -51, 81, -93, 38, -63, 91, 18, -99, 23, -19, -52, 85, 56, 8, -6, 36, 86, -2, -15, -100, -31, -28, 89, -60, -99, -76, -76, -82, -29, 84, 27, 97, -46, 86, 29, 
  -60, 106, 18, 50, -66, 58, 59, 66, 107, 62, -24, 31, -54, 0, -95, 11, -32, -12, 75, -27, 30, 10, -34, 12, -35, -94, -104, 68, 110, 27, 82, 77, 106, 68, 71, 38, 14, -102, -50, 92, 96, 23, 67, 45, -96, -43, -4, 55, 6, 23, -66, 35, 73, -87, 53, -60, 72, -9, 110, 83, 
  65, -44, -46, 90, -33, -70, -54, 121, 12, 85, -4, 84, -94, 21, 70, 71, 106, -94, 28, -12, 58, 6, 17, 42, -89, 23, -45, 16, -54, 59, 89, -69, -57, -16, 113, -38, -4, 57, 18, -1, -15, 78, -3, 120, -23, 11, 30, 30, 0, 36, -19, 60, 31, -45, -82, -76, 45, -60, 67, 40, 
  4, -33, 33, -13, -94, -6, -36, 16, 30, -87, 107, -101, -38, 86, 51, 116, 110, -73, 105, -2, -81, 123, 115, -25, 47, -5, 92, -14, -49, 104, -29, -69, -50, -16, -87, -58, 9, -64, -95, 57, 80, -82, 95, 106, 71, -18, 67, -49, 86, -30, -101, -16, -85, -17, 22, -74, -39, -59, 116, -67, 
  78, -61, 84, -10, 91, -70, 11, 59, 29, 38, -7, 8, 54, -77, -56, 11, -22, -85, -75, -47, 24, -106, -54, 86, 7, -27, 22, -97, 36, -27, 49, 100, -20, 84, 74, -102, -109, -16, 92, 45, 49, 32, -6, -47, -105, -13, -72, 67, 95, -46, -68, 52, 69, 59, -23, 75, 44, -35, -4, -30, 
  -87, -32, 92, 25, 74, 81, -22, 41, 58, 2, 115, -23, -48, 36, 27, -89, -77, 111, 113, 66, -64, 98, 102, -43, -72, 98, -89, -36, -74, -107, -17, 86, 39, 58, 112, -18, 79, 4, 52, -54, -30, 95, 68, -94, 97, 63, -88, 25, 3, 87, 0, 52, -102, -81, 23, 59, 40, -32, -93, 115, 
  -66, -7, 70, -22, -62, 55, -9, -101, 46, 11, -70, -89, 72, 80, 29, -97, 42, -26, 38, -41, -31, 1, 14, -18, 11, -82, -62, -53, -31, 40, -71, 69, -55, -46, -48, -7, -76, -67, 62, -87, 51, -46, -2, 24, -85, -62, -44, -26, -40, 91, 58, 60, 63, -17, 31, 59, -73, -82, -107, -71, 
  -59, 3, 51, 4, -17, -2, -57, -65, 44, 88, -20, 27, 70, -23, -30, -85, 93, 71, -76, 45, 39, -101, -103, 97, 86, 11, -81, -99, -104, -26, 65, 23, 82, -7, 17, -30, -26, 81, 58, -4, 21, 25, -90, 14, 101, 45, -67, -39, -65, -99, 0, -20, 89, 46, 21, -13, 15, -103, -52, 44, 
  41, 79, -58, -96, 9, -68, -33, -39, -96, 72, 50, -75, -106, -96, -64, 87, -67, -50, 36, 23, 85, 38, 16, -36, -7, -71, -68, -39, 42, 49, 86, 27, -41, -75, -52, -63, 13, 34, -81, -61, -52, 58, 70, 76, 75, 32, -110, 32, 9, -4, 76, 63, 28, 23, -41, -71, 11, 16, -84, 82, 
  44, -106, 83, -36, -49, 26, 54, -54, -103, -84, -33, 60, 28, -10, 26, 29, 25, 93, 6, -47, -93, 14, -49, 25, -6, -30, 58, -32, -32, 45, -45, 22, -61, 101, 69, -60, -4, -102, -100, -74, -97, -7, -108, -3, -41, -8, -106, 89, 18, -82, 80, 78, -94, -107, 83, -32, -23, 6, 76, 73, 
  -15, -21, -55, 48, -1, -90, -48, 44, -85, -36, -2, -18, -6, 8, -91, 75, -105, -105, 34, 21, 69, -31, 19, 51, -37, 36, -45, 47, 46, -41, -66, 3, 91, -33, 44, 65, -50, -46, -67, 82, -39, -97, -95, 11, 97, -70, -92, 26, -50, 65, -66, 66, 95, -101, -68, -29, -14, 57, -13, -83, 
  2, -95, 8, -80, 15, 17, 81, 65, -94, -68, -25, 34, -71, -96, 55, 21, 62, 7, -89, -49, -68, -63, -58, -80, -87, -89, 12, -61, 38, -68, 98, -12, 2, -87, -101, -85, -18, -26, 33, 60, 16, 66, -55, -27, 64, 74, -87, -63, -52, 57, -73, 11, -38, -105, 81, -63, 41, -7, -103, 85, 
  70, -88, -48, 97, -26, 54, -61, -16, -10, 11, 51, -45, 60, 39, -75, 59, -13, -15, -50, -89, -80, -33, 25, 63, -76, -36, 115, 28, 86, -36, 10, 49, -62, -102, 89, 87, 77, 44, -101, -14, -51, -57, -28, -27, 5, 85, -15, 57, -5, -3, -9, 58, -43, 59, 11, -93, -61, 13, 117, 111, 
  111, 20, 45, -62, -73, -106, 63, 62, 73, 35, 91, -105, -45, 0, 2, 47, 105, 32, -70, -90, -18, 77, 60, -49, -31, 80, 3, -67, 53, 14, -77, -79, -73, -99, 93, 61, 87, -60, 18, -66, 60, -58, -99, 27, 117, -3, -95, 34, 72, -96, -79, -74, -1, -18, -18, -25, -80, 32, 37, -80, 
  6, -43, 45, -38, 83, -31, 20, 95, 0, -13, -28, 96, 15, 95, 46, -55, -37, -23, -5, 111, 120, -54, -47, 1, 35, 15, 34, 87, -20, 115, -68, 5, -27, 14, -67, -103, 30, 80, -95, -39, 89, 11, 90, 11, 25, -45, 43, -39, -91, 60, 113, -25, 87, -82, 36, -87, 70, 99, 108, -39, 
  -41, 16, 45, -93, 46, -77, 44, 49, 74, -2, 1, 44, -15, 66, -15, 97, 109, 32, -46, -15, -89, 77, 89, -29, 65, -86, -2, -46, 82, -32, 77, -94, -84, -42, -4, -11, 81, 85, 104, -76, 51, 77, 82, 90, -99, 95, 72, -43, 48, 67, 80, 101, -48, 97, 81, -14, 40, -19, -43, -58, 
  59, 85, 65, -61, 9, -9, 7, 77, 72, 98, -7, -76, -16, -98, 48, -89, 101, -97, 95, -63, 74, -70, -35, 27, -19, -36, -91, 5, -12, 58, -82, -93, 100, -1, 118, 65, -97, 89, 15, 115, 2, 13, 4, 75, 106, 73, -75, 53, 78, 115, 69, 76, 48, 5, -33, 62, -68, -105, -30, -50, 
  -73, -27, 41, -18, -32, -94, 77, 23, -30, -99, 36, 66, -22, -35, 114, -33, 18, 23, 15, -107, -19, -42, 4, 52, -50, 111, -36, -89, -95, -42, 90, 45, 97, 27, 38, 68, -43, 11, -64, -6, -97, -66, 91, -16, -36, 24, 3, -20, 47, 109, 12, -50, -80, -82, -22, -106, 88, -18, 7, 79, 
  53, -102, 100, 44, 76, -57, 106, -6, -70, -20, -24, -63, -90, -103, 58, 81, -21, 48, 1, 56, -96, -106, 26, -11, 18, -66, 74, 15, 9, -62, 70, 4, -47, -39, 76, -84, -102, 84, -59, -44, 34, 52, -30, 52, 24, -107, -89, 52, -91, -59, -105, 47, 85, -21, 14, -34, -20, -39, -54, 24, 
  52, -21, 30, 89, -28, 59, -99, 111, -76, 101, -38, 100, 125, 42, 101, 22, 84, 1, 106, 60, -90, -38, -10, -45, -35, 7, 94, 52, 48, -80, -84, -106, -97, -26, -74, 57, 46, 29, -71, -87, -10, 54, 98, 47, -20, -66, -76, -94, -26, 30, -75, -7, 68, -6, -25, 84, -12, 87, 117, 20, 
  4, 13, 51, -15, 74, 17, 6, -70, 102, 60, -102, 109, -24, 75, 92, 90, -9, 72, 110, -15, 26, 96, -52, 97, -80, 108, 7, 10, 93, 14, 57, 45, -3, 85, -90, 24, -60, 83, 30, 56, -11, 17, 111, -55, 24, 18, -35, 63, 21, 111, -100, 6, -53, 61, -13, 107, 31, 110, 4, 4, 
};
const TfArray<2, int> tensor_dimension8 = { 2, { 40,60 } };
const TfArray<1, float> quant8_scale = { 1, { 0.0021971287205815315, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[60] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, };
const TfArray<1, int> tensor_dimension9 = { 1, { 60 } };
const TfArray<1, float> quant9_scale = { 1, { 4.8590416554361582e-05, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[60*18] = { 
  0, 83, 25, -78, -81, 83, -47, -22, -90, -43, 29, -80, -62, -58, -74, 75, -62, -87, 
  -94, 17, 29, 86, 7, -54, 93, -13, 51, 70, -13, 91, -79, -41, 88, -28, 14, -7, 
  66, -66, 55, -13, -67, 67, 2, -86, 13, 42, -49, -71, -83, -77, -90, -23, 31, -14, 
  -91, 61, -10, -88, 53, -28, 47, 47, 61, 61, -55, -48, 114, 89, 9, -87, 58, -4, 
  75, -56, 79, 54, -63, 56, -14, 91, -32, 60, 43, -71, -29, 56, -82, -63, -26, 81, 
  -28, -6, 13, 28, -105, -3, -28, -76, 69, -3, -23, -58, 65, 90, -71, -100, -8, -16, 
  44, -58, -35, 4, 10, -15, 101, 23, -38, -85, 61, -3, -90, 96, 2, -85, -10, 84, 
  78, 85, 22, 82, -39, -101, -67, -56, -35, 23, 19, -92, -21, -40, 127, -7, -62, -27, 
  51, -21, -4, -23, 58, -40, 107, 73, 59, -11, 59, -5, -83, 9, -85, 32, -58, -94, 
  -81, -3, -90, -101, -95, 82, 71, 69, 95, 29, -45, -5, 69, 16, -52, -99, 89, 98, 
  102, -98, 51, 31, 30, -56, 29, 56, 82, -33, -96, -18, -37, 16, 17, 73, 64, -69, 
  -17, -32, 95, -30, 57, 49, 97, -28, 31, 37, -11, -36, -65, 76, 80, -20, -90, 66, 
  -47, -33, -57, 58, 22, 71, 89, 51, 51, -47, -42, 86, 97, -60, -79, -43, -17, -88, 
  17, -9, -101, 31, 104, -70, -79, -79, -56, 80, 21, -103, 54, -30, 107, -49, 111, 45, 
  89, 13, -41, 34, -86, -40, 55, 97, -102, -81, 99, 61, -84, -104, -97, 60, -105, 43, 
  -3, -92, -19, 23, -55, 73, 33, 72, 25, -38, 26, 48, 6, 87, 21, -63, -71, -7, 
  -3, -6, -30, -94, 14, 37, 55, -55, 39, 79, 38, -61, 28, 10, 13, -84, -9, -18, 
  -21, 67, -43, -9, -37, -30, 98, -38, -55, 22, -22, 26, 105, -82, 101, -64, -77, -53, 
  -85, -100, -63, -41, -94, -51, -53, 80, -48, -32, 38, -88, 20, -35, -64, -1, -80, -95, 
  -6, -54, 30, 72, 83, -45, -57, -92, -15, -52, -77, -68, -91, -18, 36, -80, -13, 55, 
  -14, 28, -58, -3, -64, 22, -44, 77, 58, -63, 27, -93, 81, 57, -30, -38, -73, 42, 
  -11, -27, 31, -61, 21, 84, -58, 79, 48, -36, 95, 81, -12, -48, 84, 88, -2, 1, 
  -15, 46, 98, -88, 49, 31, 46, 79, -29, -55, 71, -20, -8, 55, -16, -53, -29, -25, 
  49, -11, 93, 73, 66, -73, 67, -60, 51, 84, 45, 61, -92, -86, 80, 2, 41, -22, 
  18, -76, -22, -27, -42, 51, -21, -19, 7, -89, -59, -32, -87, 16, -35, 62, 63, -74, 
  73, -42, 111, -101, 49, -97, 6, -2, -32, -57, -16, 31, -63, 67, -26, -76, 62, 34, 
  -26, -60, 59, -5, 59, -41, 68, -43, -3, 69, -90, -76, 41, -6, -3, 87, -18, -85, 
  -102, 90, 43, -18, 48, -41, 103, -52, 92, -94, 87, -35, 23, -20, 100, 23, 47, -22, 
  105, -88, -65, 1, -34, 47, 25, 88, 76, 72, -101, -80, 101, -47, -37, -39, 30, 115, 
  40, -66, 2, -94, -33, -13, -64, 23, 60, -4, -36, 71, 75, 20, 34, 69, -84, -99, 
  26, -77, 13, -74, -75, 1, 32, -88, -13, 65, -74, 97, -76, 50, -31, 4, 32, -15, 
  28, -72, -39, 84, 120, -41, 6, 95, 42, 104, -22, 30, 26, 46, -12, 32, -10, 35, 
  -108, 65, -93, -26, 72, 10, -28, -61, -36, 93, 16, 56, -68, -19, -45, 102, 95, -106, 
  -98, 86, 87, 16, 25, -97, -38, -7, -99, -18, -94, -12, -6, 89, -73, -4, 61, -70, 
  -80, 14, 34, 89, 93, -90, -78, -50, -57, 87, -52, -15, 20, -97, 58, -38, -32, 42, 
  97, -99, 20, -8, 37, 22, 78, -82, -5, -17, -38, -8, -96, 66, -76, -89, 72, 69, 
  -65, 99, -78, -86, 67, -77, -30, 38, -30, -83, -9, -33, -81, 1, 93, 94, -48, -30, 
  54, 70, 83, -33, 65, -67, -62, -72, -81, -13, -85, 5, -51, -93, -32, 20, 43, 87, 
  -24, 57, -8, -86, -69, 5, 37, -53, -86, -87, -38, 92, -64, -72, 56, 90, -90, 57, 
  74, -14, -10, -79, -3, -1, 24, 72, 1, 41, 16, 3, 17, -63, 51, -92, 0, -73, 
  -32, 46, 26, 31, -14, 75, 95, 25, -49, -93, 61, 44, -6, -8, -79, 86, -17, -23, 
  80, 20, 36, 36, 60, 46, -25, -23, -18, -75, 82, -30, 26, -46, 50, -67, -85, -34, 
  -95, -62, 103, 6, -59, 63, 115, -81, 85, -83, 45, -34, 61, 54, 44, -82, 42, -2, 
  -48, 56, 46, 74, 40, -45, -63, -36, -69, 63, 92, 8, 28, 57, 95, -62, -63, -95, 
  19, -85, -48, 23, -69, 75, -18, -10, 65, -88, 85, -54, 14, 19, 68, 64, 58, -29, 
  15, -79, -36, -39, 13, 32, -76, -51, 19, 102, 74, -95, 49, 40, 20, -67, 94, -40, 
  -35, -112, -38, -6, 39, -52, -50, 63, 111, 22, -4, 63, -77, 16, -48, -56, -72, 57, 
  30, 31, -34, 89, -60, -52, 69, -4, -23, -18, 29, -91, 60, 23, 27, -81, -68, 20, 
  53, 63, -10, 58, 18, -47, 93, 43, 74, -92, -18, -34, -69, -63, -81, -9, -96, -72, 
  -98, 70, -54, -72, -63, 50, -19, 99, -7, 59, -81, 27, -20, 39, -45, 52, 61, -100, 
  46, -36, -1, 36, 53, -5, -86, 69, -47, 74, -77, 77, -77, -14, -28, -92, -27, -12, 
  85, -84, 67, 88, -36, -34, -28, 2, 61, 43, 8, -22, 24, 74, -50, 41, -73, 31, 
  6, -85, -79, -91, -33, -32, 43, 57, 7, -24, -94, 53, -82, 17, -97, 48, 58, 18, 
  -49, 89, -5, 40, -25, -19, -77, -35, -57, 12, -66, 22, 79, 46, 79, 50, 29, -51, 
  -56, -59, 38, -98, -97, 17, 75, 71, -8, -36, -44, -62, 81, 78, -14, -62, -16, -25, 
  -73, 28, 40, 43, 41, 40, -89, 38, -41, -55, -29, 28, 26, -44, 64, -26, 46, 83, 
  -35, -21, 32, -29, -31, -45, -85, -41, -14, 64, 78, -50, -40, -14, -10, -90, 4, -70, 
  82, -31, 27, 94, -68, 32, 50, 113, -52, -59, -3, 112, 80, -37, 34, 94, -56, 58, 
  62, 4, -9, -46, -74, -48, -47, 81, 6, -72, -62, 86, -76, 29, 0, 21, 5, -53, 
  1, -40, 82, 91, 11, -83, -36, -77, -71, 87, 86, 43, 5, -82, 8, 44, 32, 31, 
};
const TfArray<2, int> tensor_dimension10 = { 2, { 60,18 } };
const TfArray<1, float> quant10_scale = { 1, { 0.0026646992191672325, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension11 = { 2, { 1,60 } };
const TfArray<1, float> quant11_scale = { 1, { 0.012240322306752205, } };
const TfArray<1, int> quant11_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&quant11_zero, 0 };
const TfArray<2, int> tensor_dimension12 = { 2, { 1,40 } };
const TfArray<1, float> quant12_scale = { 1, { 0.0085812695324420929, } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension13 = { 2, { 1,20 } };
const TfArray<1, float> quant13_scale = { 1, { 0.008096267469227314, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension14 = { 2, { 1,10 } };
const TfArray<1, float> quant14_scale = { 1, { 0.0052904337644577026, } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension15 = { 2, { 1,2 } };
const TfArray<1, float> quant15_scale = { 1, { 0.007274591363966465, } };
const TfArray<1, int> quant15_zero = { 1, { 70 } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&quant15_zero, 0 };
const TfArray<1, float> quant16_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,10,9 } };
const TfArray<1, int> outputs0 = { 1, { 11 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 11,8,7 } };
const TfArray<1, int> outputs1 = { 1, { 12 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 12,6,5 } };
const TfArray<1, int> outputs2 = { 1, { 13 } };
const TfLiteFullyConnectedParams opdata3 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs3 = { 3, { 13,4,3 } };
const TfArray<1, int> outputs3 = { 1, { 14 } };
const TfLiteFullyConnectedParams opdata4 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs4 = { 3, { 14,2,1 } };
const TfArray<1, int> outputs4 = { 1, { 15 } };
const TfLiteSoftmaxParams opdata5 = { 1 };
const TfArray<1, int> inputs5 = { 1, { 15 } };
const TfArray<1, int> outputs5 = { 1, { 16 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension0, 18, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 160, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 2400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 240, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 1080, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension11, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension12, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension13, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension14, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension15, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension15, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[6] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[6] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 17, };
const size_t tflNodes_subgraph_index[] = {0, 6, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  16, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1096455_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 17;
  for (size_t i = 0; i < 17; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1096455_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1096455_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1096455_5_invoke() {
  for (size_t i = 0; i < 6; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1096455_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
