/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include <vector>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1096455_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1096455_1[] = { "0", "1" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1096455_4_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 };
const uint32_t ei_dsp_config_1096455_4_axes_size = 18;
ei_dsp_config_raw_t ei_dsp_config_1096455_4 = {
    4, // uint32_t blockId
    1, // int implementationVersion
    18, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_1096455_4[18] = { 53.58867388602876, 259.7741878217646, 74.95934670690572, 0.6543582460500622, 0.4933428013491923, 0.893839872181786, 0.5064796733534529, 0.5964849991123735, 10.01179587867942, 0.4926327001597728, 0.49884608556719334, 5.442215515710989, 5.952073472715516, 158969.78270903605, 28.876216974432804, 419.4173619740813, 3.461743298420025, 7.0278714716847155 };
const float ei_dn_standard_scaler_scale_1096455_4[18] = { 0.046985433929484614, 0.012394287604988624, 0.04887881392916741, 2.1027086923725964, 2.0001772967483227, 3.2463057559530593, 2.0001679658240854, 2.03831074876342, 0.17276365116848072, 2.0002171437861933, 2.0000053260953456, 0.3494086969969215, 0.28804269873488836, 0.000012356589203886026, 0.1585642184908126, 0.004458596256216804, 0.439156103854646, 0.5051075639790137 };
const float ei_dn_standard_scaler_var_1096455_4[18] = { 452.97425126822833, 6509.638339589788, 418.5609249770785, 0.22617353187635023, 0.24995568170612348, 0.09489015507983428, 0.2499580138332335, 0.24069064494628561, 33.50389140898563, 0.24994572289306405, 0.2499986684814825, 8.190918010006046, 12.052753025382442, 6549419107.550511, 39.7731160325155, 50304.13736587945, 5.185159893628528, 3.919514322553801 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1096455_4 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1096455_4,
    .mean_data_len = 18,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1096455_4,
    .scale_data_len = 18,
    .var_data = (float *)ei_dn_standard_scaler_var_1096455_4,
    .var_data_len = 18
};
ei_data_normalization_t ei_data_normalization_config_1096455_4 = {
    (void *) &ei_data_normalization_standard_scaler_config_1096455_4, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1096455_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1096455_1[ei_dsp_blocks_1096455_1_size] = {
    { // DSP block 4
        4,
        18, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_1096455_4, // pointer to config struct
        ei_dsp_config_1096455_4_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1096455_4_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1096455_4, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1096455_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1096455_5_init,
    .model_invoke = &tflite_learn_1096455_5_invoke,
    .model_reset = &tflite_learn_1096455_5_reset,
    .model_input = &tflite_learn_1096455_5_input,
    .model_output = &tflite_learn_1096455_5_output,
};

const uint8_t ei_output_tensors_indices_1096455_5[1] = { 0 };
const uint8_t ei_output_tensors_size_1096455_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1096455_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_1096455_5,
    .output_tensors_size = ei_output_tensors_size_1096455_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1096455_5,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1096455_1_size = 1;
const uint32_t ei_learning_block_1096455_5_inputs[1] = { 4 };
const uint8_t ei_learning_block_1096455_5_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1096455_1[ei_learning_blocks_1096455_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1096455_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1096455_5_inputs,
        ei_learning_block_1096455_5_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1096455_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1096455_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1096455_1[ei_postprocessing_blocks_1096455_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1096455_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_1096455_1_size = 0;

uint32_t *freeform_outputs_1096455_1 = nullptr;

const ei_impulse_t impulse_1096455_1 = {
    .project_id = 1096455,
    .project_owner = "singularity",
    .project_name = "singularity-project-1",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 18,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 18,
    .dsp_input_frame_size = 1 * 18,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_1096455_1_size,
    .dsp_blocks = ei_dsp_blocks_1096455_1,

    .learning_blocks_size = ei_learning_blocks_1096455_1_size,
    .learning_blocks = ei_learning_blocks_1096455_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1096455_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1096455_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "Age + Cholesterol + Heart Rate + Diabetes + Family History + Smoking + Obesity + Alcohol Consumption + Exercise Hours Per Week + Previous Heart Problems + Medication Use + Stress Level + Sedentary Hours Per Day + Income + BMI + Triglycerides + Physical Activity Days Per Week + Sleep Hours Per Day",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_1096455_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1096455_1_size,
    .freeform_outputs = freeform_outputs_1096455_1
};

ei_impulse_handle_t impulse_handle_1096455_1 = ei_impulse_handle_t( &impulse_1096455_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1096455_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1096455_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1096455_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1096455_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
